/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /** Health check */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/auth/register": {
    /** Register user */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterRequest"];
        };
      };
      responses: {
        /** @description Registered */
        201: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
      };
    };
  };
  "/auth/login": {
    /** Login */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Logged in */
        200: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
      };
    };
  };
  "/auth/logout": {
    /** Logout (invalidate token) */
    post: {
      responses: {
        /** @description Logged out */
        204: {
          content: never;
        };
      };
    };
  };
  "/wallet/me": {
    /** Get current user's wallet */
    get: {
      responses: {
        /** @description Wallet */
        200: {
          content: {
            "application/json": components["schemas"]["Wallet"];
          };
        };
      };
    };
  };
  "/wallet/deposit": {
    /** Deposit funds */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["DepositRequest"];
        };
      };
      responses: {
        /** @description Updated wallet */
        200: {
          content: {
            "application/json": components["schemas"]["Wallet"];
          };
        };
      };
    };
  };
  "/ai/deposit-agent": {
    /** Get AI-guided deposit recommendation */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["DepositAgentRequest"];
        };
      };
      responses: {
        /** @description Deposit recommendation */
        200: {
          content: {
            "application/json": components["schemas"]["DepositAgentResponse"];
          };
        };
      };
    };
  };
  "/ai/copilot-chat": {
    /** Chat with the wallet AI copilot */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CopilotChatRequest"];
        };
      };
      responses: {
        /** @description Copilot response */
        200: {
          content: {
            "application/json": components["schemas"]["CopilotChatResponse"];
          };
        };
      };
    };
  };
  "/transfer": {
    /** Transfer funds to another user */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["TransferRequest"];
        };
      };
      responses: {
        /** @description Transfer result */
        200: {
          content: {
            "application/json": components["schemas"]["TransferResult"];
          };
        };
      };
    };
  };
  "/transactions": {
    /** List transactions */
    get: {
      parameters: {
        query?: {
          limit?: number;
        };
      };
      responses: {
        /** @description Transactions */
        200: {
          content: {
            "application/json": components["schemas"]["Transaction"][];
          };
        };
      };
    };
  };
  "/security/login-events": {
    /** Record login event and request anomaly score */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginEvent"];
        };
      };
      responses: {
        /** @description AI score */
        200: {
          content: {
            "application/json": components["schemas"]["AnomalyScore"];
          };
        };
      };
    };
  };
  "/security/alerts": {
    /** List security alerts for current user */
    get: {
      responses: {
        /** @description Alerts */
        200: {
          content: {
            "application/json": components["schemas"]["SecurityAlert"][];
          };
        };
      };
    };
  };
  "/admin/users": {
    /** Admin list users */
    get: {
      responses: {
        /** @description Users */
        200: {
          content: {
            "application/json": components["schemas"]["User"][];
          };
        };
      };
    };
  };
  "/admin/alerts": {
    /** Admin list alerts */
    get: {
      responses: {
        /** @description Alerts */
        200: {
          content: {
            "application/json": components["schemas"]["SecurityAlert"][];
          };
        };
      };
    };
  };
  "/admin/audit-logs": {
    /** Admin list audit logs */
    get: {
      responses: {
        /** @description Audit logs */
        200: {
          content: {
            "application/json": components["schemas"]["AuditLog"][];
          };
        };
      };
    };
  };
  "/admin/policies": {
    /** Admin get security policies */
    get: {
      responses: {
        /** @description Policies */
        200: {
          content: {
            "application/json": components["schemas"]["SecurityPolicy"][];
          };
        };
      };
    };
    /** Admin update policy */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SecurityPolicy"];
        };
      };
      responses: {
        /** @description Updated */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      id: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "USER" | "ADMIN";
    };
    Wallet: {
      id: string;
      /** Format: double */
      balance: number;
      /** @default USD */
      currency: string;
    };
    Transaction: {
      id: string;
      /** Format: double */
      amount: number;
      type: string;
      description?: string;
      /** Format: date-time */
      createdAt: string;
    };
    RegisterRequest: {
      /** Format: email */
      email: string;
      password: string;
      /** @enum {string} */
      role: "USER" | "ADMIN";
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    AuthResponse: {
      token?: string;
      user?: components["schemas"]["User"];
    };
    DepositRequest: {
      /** Format: double */
      amount: number;
    };
    DepositAgentRequest: {
      goal: string;
      /**
       * Format: double
       * @default 0
       */
      currentBalance?: number;
      /** @default USD */
      currency?: string;
      /** Format: double */
      monthlyIncome?: number;
      /** Format: double */
      monthlyExpenses?: number;
    };
    DepositAgentResponse: {
      /** Format: double */
      recommendedAmount: number;
      reasoning: string[];
      /** @enum {string} */
      riskLevel: "low" | "medium" | "high";
      nextAction: string;
      /** Format: double */
      confidence: number;
    };
    TransferRequest: {
      toUserId: string;
      /** Format: double */
      amount: number;
    };
    TransferResult: {
      status?: string;
      transaction?: components["schemas"]["Transaction"];
    };
    LoginEvent: {
      userId: string;
      ipAddress: string;
      userAgent?: string;
      /** Format: date-time */
      timestamp: string;
    };
    AnomalyScore: {
      /** Format: double */
      score?: number;
      reasons?: string[];
    };
    CopilotMessage: {
      /** @enum {string} */
      role: "user" | "assistant" | "system";
      content: string;
    };
    CopilotTransaction: {
      /** Format: double */
      amount: number;
      type: string;
      description?: string;
      /** Format: date-time */
      createdAt: string;
      /** @enum {string} */
      direction: "credit" | "debit";
    };
    CopilotChatRequest: {
      /** @default USD */
      currency?: string;
      /**
       * Format: double
       * @default 0
       */
      currentBalance?: number;
      /** Format: double */
      monthlyIncome?: number;
      /** Format: double */
      monthlyExpenses?: number;
      recentTransactions?: components["schemas"]["CopilotTransaction"][];
      messages: components["schemas"]["CopilotMessage"][];
    };
    CopilotChatResponse: {
      reply: string;
      topic: string;
      suggestedActions: string[];
      /** Format: double */
      suggestedDepositAmount?: number | null;
      /** @enum {string} */
      riskLevel: "low" | "medium" | "high";
      /** Format: double */
      confidence: number;
      followUpQuestion?: string | null;
    };
    SecurityAlert: {
      id?: string;
      type?: string;
      message?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    AuditLog: {
      id?: string;
      action?: string;
      actor?: string;
      details?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    SecurityPolicy: {
      id?: string;
      maxLoginAttempts?: number;
      lockoutMinutes?: number;
      rateLimitPerMin?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
